#!/bin/sh

set -eu

any_metered=0
quiet=0

case "$@" in
-q|--quiet)
    quiet=1
    ;;
*)
    echo "Unknown arguments: $@" >2
    ;;
esac

for dev in `nmcli -t -f DEVICE c show --active`; do
    metered=`nmcli -t -f GENERAL.METERED dev show "$dev" | cut -d ':' -f 2`
    case "$metered" in
    yes*)
        any_metered=1
        test $quiet = 1 || echo "$dev $metered"
        ;;
    esac
done

if [ "$any_metered" = '1' ]; then
    exit 0
else
    exit 1
fi
